name: Telegram Notification
on:
  push:
  fork:
  watch:
  issues:
    types: [created, closed, opended, reopened, locked, unlocked]
  issue_comment:
    types: [created, deleted]
  pull_request:
    types: [created, closed, opened, reopened, locked, unlocked, synchronize]
  pull_request_target:
    types: [created, closed, opened, reopened, locked, unlocked, synchronize]
  pull_request_review_comment:
    types: [created, deleted]
  release:
    types: [published, released]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - name: Notify everything on Telegram
          uses: EverythingSuckz/github-telegram-notify@main
          with:
            bot_token: "6965301277:AAH2qvUpcsieNaYc1VLvtnPmPCDHiyc45F4"
            chat_id: "-4657642655"
            topic_id: '${{ secrets.TELEGRAM_TOPIC_ID }}'
